name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    outputs:
      image-tag: ${{ steps.deploy.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
      
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::640786919619:role/Github-Ci-CD
          aws-region: eu-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Get latest image from ECR
        id: get-image
        env:
          ECR_REPOSITORY_STAGE: nebo_task_stage
          
        run: |
          LATEST_TAG=$(aws ecr describe-images \
            --repository-name $ECR_REPOSITORY_STAGE \
            --output json | \
            jq -r '.imageDetails | 
              map(select(.imageTags != null)) | 
              map(select(.imageTags[] | startswith("stage_"))) | 
              sort_by(.imagePushedAt) | 
              last | 
              .imageTags[] | 
              select(startswith("stage_"))' || echo "")
          
          if [ -z "$LATEST_TAG" ]; then
            echo "ERROR: No dev_ image found in ECR"
            exit 1
          fi
          
          echo "Latest image tag: $LATEST_TAG"
          echo "image-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          
      - name: Deploy
        id: deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_STAGE: nebo_task_stage
          ECR_REPOSITORY_PROD: nebo_task
        run: |
          LATEST_TAG="${{ steps.get-image.outputs.image-tag }}"
          
          echo "Pulling image: $ECR_REGISTRY/$ECR_REPOSITORY_STAGE:${LATEST_TAG}"
          docker pull "$ECR_REGISTRY/$ECR_REPOSITORY_STAGE:${LATEST_TAG}"
          
          NEW_TAG="${LATEST_TAG/stage_/release_candidate_}"
          
          echo "Creating new tag: $NEW_TAG"
          docker tag "$ECR_REGISTRY/$ECR_REPOSITORY_STAGE:${LATEST_TAG}" "$ECR_REGISTRY/$ECR_REPOSITORY_PROD:$NEW_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY_PROD:$NEW_TAG"
          
          echo "Successfully pushed: $NEW_TAG"
          echo "image-tag=$NEW_TAG" >> $GITHUB_OUTPUT
  
  test:
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/unit_test.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
      aws-role-arn: arn:aws:iam::640786919619:role/Github-Ci-CD
    secrets: inherit
