name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    outputs:
      image-tag: ${{ steps.deploy.outputs.image-tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::640786919619:role/Github-Ci-CD
          aws-region: eu-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.1.4
      
      - name: Get latest image from ECR
        id: get-image
        env:
          ECR_REPOSITORY_STAGE: nebo_task_stage
          
        run: |
          LATEST_TAG=$(aws ecr describe-images \
            --repository-name $ECR_REPOSITORY_STAGE \
            --output json | \
            jq -r '.imageDetails | 
              map(select(.imageTags != null)) | 
              map(select(.imageTags[] | startswith("stage_"))) | 
              sort_by(.imagePushedAt) | 
              last | 
              .imageTags[] | 
              select(startswith("stage_"))' || echo "")
          
          if [ -z "$LATEST_TAG" ]; then
            echo "ERROR: No dev_ image found in ECR"
            exit 1
          fi
          
          echo "Latest image tag: $LATEST_TAG"
          #
          echo "image-tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          
      - name: Deploy
        id: deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_STAGE: nebo_task_stage
          ECR_REPOSITORY_PROD: nebo_task
        run: |
          LATEST_TAG="${{ steps.get-image.outputs.image-tag }}"
          
          echo "Pulling image: $ECR_REGISTRY/$ECR_REPOSITORY_STAGE:${LATEST_TAG}"
          docker pull "$ECR_REGISTRY/$ECR_REPOSITORY_STAGE:${LATEST_TAG}"
          
          NEW_TAG="${LATEST_TAG/stage_/release_candidate_}"
          
          echo "Creating new tag: $NEW_TAG"
          docker tag "$ECR_REGISTRY/$ECR_REPOSITORY_STAGE:${LATEST_TAG}" "$ECR_REGISTRY/$ECR_REPOSITORY_PROD:$NEW_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY_PROD:$NEW_TAG"
          
          echo "Successfully pushed: $NEW_TAG"
          echo "image-tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: ECR Image Scan & Enforcement
        id: scan
        env:
          ECR_REPOSITORY_PROD: nebo_task
        run: |
          NEW_TAG="${{ steps.deploy.outputs.image-tag }}"
          
          echo "Checking vulnerabilities for: $NEW_TAG"

          aws ecr start-image-scan --repository-name $ECR_REPOSITORY_PROD --image-id imageTag=$NEW_TAG || true
          
          aws ecr wait image-scan-complete --repository-name $ECR_REPOSITORY_PROD --image-id imageTag=$NEW_TAG
          
          FINDINGS=$(aws ecr describe-image-scan-findings --repository-name $ECR_REPOSITORY_PROD --image-id imageTag=$NEW_TAG)
          
          CRITICAL=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.CRITICAL // 0')
          HIGH=$(echo $FINDINGS | jq '.imageScanFindings.findingSeverityCounts.HIGH // 0')
          
          echo "Scan Summary: $CRITICAL Critical, $HIGH High vulnerabilities found."

          if [ "$CRITICAL" -gt 0 ]; then
            echo "::error::Pipeline failed due to $CRITICAL critical vulnerabilities in ECR image."
            exit 1
          fi
  
  test:
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/unit_test.yml
    with:
      image-tag: ${{ needs.build.outputs.image-tag }}
      aws-role-arn: arn:aws:iam::640786919619:role/Github-Ci-CD
    secrets: inherit
