name: Send email

on:
  push:
    branches: [ "Stage" ]
  workflow_run:
    workflows: ["Docker Image CI", "SonarQube Nebo-Testing", "Unit Test"]
    types: 
      - completed

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get secrets from AWS Secrets Manager using CLI
        run: |
          # Get EMAIL_SENDER
          EMAIL_SENDER=$(aws secretsmanager get-secret-value \
            --secret-id user_data/email_sender \
            --query SecretString \
            --output text | jq -r '.email')
          echo "::add-mask::$EMAIL_SENDER"
          echo "EMAIL_SENDER=$EMAIL_SENDER" >> $GITHUB_ENV
          
          # Get EMAIL_PASSWORD
          EMAIL_PASSWORD=$(aws secretsmanager get-secret-value \
            --secret-id user_data/password \
            --query SecretString \
            --output text | jq -r '.password')
          echo "::add-mask::$EMAIL_PASSWORD"
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> $GITHUB_ENV
          
          # Get EMAIL_RECIPIENT
          EMAIL_RECIPIENT=$(aws secretsmanager get-secret-value \
            --secret-id user_data/email \
            --query SecretString \
            --output text | jq -r '.email')
          echo "::add-mask::$EMAIL_RECIPIENT"
          echo "EMAIL_RECIPIENT=$EMAIL_RECIPIENT" >> $GITHUB_ENV

      - name: Debug AWS secrets
        run: |
          echo "EMAIL_SENDER is set: ${{ env.EMAIL_SENDER != '' }}"
          echo "EMAIL_PASSWORD is set: ${{ env.EMAIL_PASSWORD != '' }}"
          echo "EMAIL_RECIPIENT is set: ${{ env.EMAIL_RECIPIENT != '' }}"
          
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ env.EMAIL_SENDER }}
          password: ${{ env.EMAIL_PASSWORD }}
          subject: "🚀 Build ${{ job.status }} for ${{ github.repository }}"
          to: ${{ env.EMAIL_RECIPIENT }}
          from: "GitHub Actions <${{ env.EMAIL_SENDER }}>"
          body: |
            Hello ${{ env.EMAIL_RECIPIENT }},
          
            The workflow **${{ github.event.workflow_run.name }}** for ${{ github.repository }}
            on branch ${{ github.event.workflow_run.head_branch }} has finished with status **${{ github.event.workflow_run.conclusion }}**.
            Commit ID: ${{ github.sha }}
            Pushed by: ${{ github.actor }}
          
            🔗 Run details: ${{ github.event.workflow_run.html_url }}
          
            Best,
            GitHub Actions Bot
