name: Send email
on:
  push:
    branches: [ "main", "stage", "dev-*" ]
  workflow_run:
    workflows: ["Docker Image CI", "SonarQube Nebo-Testing"]
    types: 
      - completed
  
jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            EMAIL_SENDER,user_data/email_sender
            EMAIL_PASSWORD,user_data/password
            EMAIL_RECIPIENT,user_data/email
      - name: Debug AWS secrets
        run: |
          printenv | grep SECRET_
          
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ env.EMAIL_SENDER }}
          password: ${{ env.EMAIL_PASSWORD }}
          subject: "🚀 Build ${{ job.status }} for ${{ github.repository }}"
          to: ${{ env.EMAIL_RECIPIENT }}
          from: "GitHub Actions <${{ env.EMAIL_SENDER }}>"
          body: |
            Hello ${{ env.EMAIL_RECIPIENT }},
            The build for ${{ github.repository }} on branch ${{ github.ref_name }}
            has completed with status: ${{ job.status }}
      
            🔗 Run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
            Best,
            GitHub Actions Bot
