name: Unit Test

on:
  push:
    branches: [ "main", "stage", "dev-*" ]
  pull_request:
    branches: [ "main", "stage", "dev-*" ]
  workflow_run:
    workflows: ["Docker Image CI"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Read image tag
        id: read-tag
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Image tag: $IMAGE_TAG"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Pull and test Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PROD: nebo_task
          ECR_REPOSITORY_STAGE: nebo_task_stage
          BRANCH_NAME: ${{ github.ref_name }}
          IMAGE_TAG: ${{ steps.read-tag.outputs.tag }}
        run: |
          #!/bin/bash
          echo "Using image tag: $TAG_IMAGE"
          
          # Sanitize branch name
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          
          # Pull the image using TAG_IMAGE
          docker pull "$ECR_REGISTRY/$ECR_REPOSITORY_STAGE:$IMAGE_TAG"
          
          # Run the container
          docker run -d \
            --name temp-name-container \
            -p 8080:80 \
            "$IMAGE_TAG"
        
          sleep 5
        
          curl --fail http://localhost:8080
          exit_status=$?
          
          if [ $exit_status -ne 0 ]; then
            echo "Curl command failed with exit code $exit_status"
            docker logs temp-name-container
            docker stop temp-name-container
            docker rm temp-name-container
            exit $exit_status
          else
            echo "Curl command succeeded"
          fi
          
          docker stop temp-name-container
          docker rm temp-name-container
          
          # Push to PROD if main branch
          if [ "$SAFE_BRANCH" = "main" ]; then
            docker tag ${{ secrets.STAGE_REPO_LINK }}:$TAG_IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY_PROD:$IMAGE_TAG"
            docker push "$ECR_REGISTRY/$ECR_REPOSITORY_PROD:$IMAGE_TAG"
          fi
          

          
